### ISSUE TITLE
startup problem

### ISSUE THREAD

**Issue by osvaldik** [jridky/kancional-server#1]
Po upgrade rasbian nastal problem se startup.service pri startu:
pi@raspberrypi:~ $ sudo systemctl status startup
× startup.service - Startup service
     Loaded: loaded (/lib/systemd/system/startup.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-02-15 13:42:00 GMT; 15min ago
   Duration: 22.977s
    Process: 582 ExecStart=/usr/bin/startup (code=exited, status=1/FAILURE)
   Main PID: 582 (code=exited, status=1/FAILURE)
        CPU: 751ms

Feb 15 13:41:37 raspberrypi systemd[1]: Started startup.service - Startup service.
Feb 15 13:41:59 raspberrypi startup[598]: Invalid MIT-MAGIC-COOKIE-1 key
Feb 15 13:41:59 raspberrypi startup[598]: [598:598:0215/134159.807441:ERROR:ozone_platform_x11.cc(239)] Missing X server or $DISPLAY
Feb 15 13:41:59 raspberrypi startup[598]: [598:598:0215/134159.807613:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
Feb 15 13:42:00 raspberrypi systemd[1]: startup.service: Main process exited, code=exited, status=1/FAILURE
Feb 15 13:42:00 raspberrypi systemd[1]: startup.service: Failed with result 'exit-code'.

Kdyz nahodim znovu rucne tak se rozjede:
pi@raspberrypi:~ $ sudo systemctl status startup
● startup.service - Startup service
     Loaded: loaded (/lib/systemd/system/startup.service; enabled; preset: enabled)
     Active: active (running) since Thu 2024-02-15 13:59:51 GMT; 5s ago
   Main PID: 2085 (startup)
      Tasks: 79 (limit: 8734)
        CPU: 1.543s
     CGroup: /system.slice/startup.service
             ├─2085 /bin/bash /usr/bin/startup
             ├─2086 /usr/lib/chromium-browser/chromium-browser --force-renderer-accessibility --enable-remote-extensions --enable-pinch --start-fullscreen --display=:0 --flag-switches-begin --app=http://localhost
             ├─2133 /usr/lib/chromium-browser/chrome_crashpad_handler --monitor-self --monitor-self-annotation=ptype=crashpad-handler "--database=/home/pi/.config/chromium/Crash Reports" "--annotation=channel=Built on Debian >
             ├─2135 /usr/lib/chromium-browser/chrome_crashpad_handler --no-periodic-tasks --monitor-self-annotation=ptype=crashpad-handler "--database=/home/pi/.config/chromium/Crash Reports" "--annotation=channel=Built on De>
             ├─2139 "/usr/lib/chromium-browser/chromium-browser --type=zygote --no-zygote-sandbox --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guard-on-fork=enable"
             ├─2140 "/usr/lib/chromium-browser/chromium-browser --type=zygote --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guard-on-fork=enable"
             ├─2142 "/usr/lib/chromium-browser/chromium-browser --type=zygote --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guard-on-fork=enable"
             ├─2163 "/usr/lib/chromium-browser/chromium-browser --type=gpu-process --ozone-platform=x11 --display=:0 --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guar>
             ├─2168 "/usr/lib/chromium-browser/chromium-browser --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-GB --service-sandbox-type=none --crashpad-handler-pid=0 --enable-crash-reporter=,Built o>
             ├─2178 "/usr/lib/chromium-browser/chromium-browser --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-GB --service-sandbox-type=utility --crashpad-handler-pid=0 --enable-crash-reporter=,Buil>
             ├─2205 "/usr/lib/chromium-browser/chromium-browser --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guard-on-fork=enable --first-renderer-pro>
             └─2206 "/usr/lib/chromium-browser/chromium-browser --type=renderer --crashpad-handler-pid=0 --enable-crash-reporter=,Built on Debian , running on Debian 12 --change-stack-guard-on-fork=enable --ozone-platform=x11>

Feb 15 13:59:54 raspberrypi startup[2163]: [2163:2163:0215/135954.198739:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
Feb 15 13:59:54 raspberrypi startup[2163]: [2163:2163:0215/135954.198891:ERROR:gbm_wrapper.cc(75)] Failed to get fd for plane.: No such file or directory (2)
Feb 15 13:59:54 raspberrypi startup[2163]: [2163:2163:0215/135954.199025:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
Feb 15 13:59:54 raspberrypi startup[2163]: [2163:2163:0215/135954.199246:ERROR:gbm_wrapper.cc(75)] Failed to get fd for plane.: No such file or directory (2)
Feb 15 13:59:54 raspberrypi startup[2163]: [2163:2163:0215/135954.199399:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
Feb 15 13:59:54 raspberrypi startup[2086]: [2086:2150:0215/135954.305904:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "un>
Feb 15 13:59:54 raspberrypi startup[2086]: [2086:2150:0215/135954.305991:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "un>
Feb 15 13:59:55 raspberrypi startup[2086]: [2086:2146:0215/135955.917236:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "un>
Feb 15 13:59:56 raspberrypi startup[2086]: [2086:2150:0215/135956.080811:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "un>
Feb 15 13:59:56 raspberrypi startup[2086]: [2086:2150:0215/135956.080949:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "un>
lines 1-30/30 (END)

Zatim se nepodarilo prijit co to zpusobuje.

**Comment by jridky** [comment]
Problem je s tím, že ve chvíli, kdy je servisa spouštěna není k dispozici displej, na kterém by se mohl zobrazit obsah (nebo si to alespoň zařízení myslí).

Je možné, že je dané zařízení odpojené od monitoru? Můžu poprosit o zadání verze OS a verze chromia, které je na zařízení nainstalované?

**Comment by osvaldik** [comment]
Displej pripojeny je.
Linux raspberrypi 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64
Chromium 121.0.6167.155 Built on Debian , running on Debian 12

**Comment by jridky** [comment]
Dnes jsem dělal dvě nové instalace a narazil jsem na totéž. Podařilo se mi to vyřešit tak, že jsem:

- do `/lib/systemd/system/startup.service` přidal pod `[Service]` řádek `Restart=on-failure`
- v `/usr/bin/startup` doplnil `DISPLAY=:0` před volání `chromium-browser ...`

To by samo o sobě mělo stačit, narazil jsem ale ještě na problém s vypínáním obrazovky, které je na RPi4B s nejnovějším softwarem nefunkční. Zde jsem musel:
- sudo raspi-config > Advanced > místo Waylandu použít X11
- v `/boot/firmware/config.txt` zakomentovat řádek `dtoverlay=vc4-kms-v3d`

S tímto nastavením dát reboot a mělo by to opět fungovat. 

Dejte vědět, zda se podařilo.

**Comment by osvaldik** [comment]
Perfektni.

Diky

**Comment by osvaldik** [comment]
Jeste jsem zkousel novou instalaci na starsi RPI 3B s aktulani verzi Raspi a chrom.
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
Chromium 121.0.6167.155 Built on Raspbian , running on Raspbian 11

donoff.service - 100% CPU - je to ok?
![obrazek](https://github.com/jridky/kancional-server/assets/116109580/2a1adfa7-65fb-4d81-a154-d54b1d04e2b4)

pri rychlejsim prepinani to dela tohle
![IMG_20240218_195537261~2](https://github.com/jridky/kancional-server/assets/116109580/3869d9e2-36c2-42d5-8ae4-6ff2e9132b15)

**Comment by jridky** [comment]
Na 100% by donoff service běžet nemělo. Zkusím to prověřit. Co se rychlejšího přepínání týče, je to tak, že to takto zůstane, nebo se to nakonec správně překreslí? Tady bych to odhadoval na problém prohlížeče, který nestíhá vykreslovat (otázka proč, ale to je také potřeba prověřit).

**Comment by jridky** [comment]
Nahraji dnes aktualizované zdrojové kódy do repozitáře.

**Comment by jridky** [comment]
V posledním commitu je i fix pro donoff service, aby nezatěžovala CPU na 100%.
